# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-jobify-deployment-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app-jobify-env
  template:
    metadata:
      labels:
        app: backend-app-jobify-env
    spec:
      containers:
        - name: app-jobify-env
          image: sekarfeb/jobify-mern-app-latest-backend-app:latest
          ports:
            - containerPort: 5000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-app-jobify-service-env
spec:
  selector:
    app: backend-app-jobify-env 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  
  




